<a href="https://colab.research.google.com/github/danielapavas/Labs-Deep-Learning/blob/main/content/U3%20LAB%2002%20-%20Low%20level%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 3.2 - Low level `tensorflow`

In [1]:
!wget -nc --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/2021.deeplearning/main/content/init.py
import init; init.init(force_download=False);

In [48]:
from local.lib.rlxmoocapi import submit, session
import inspect
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L03.02", varname="student");

logging in as daniela.pavas1@udea.edu.co... please wait
using course session 2021.deeplearning::udea.20242
success!! you are logged in


In [3]:
!pip install tensorflow==2.15

In [20]:
import numpy as np
import os
import tensorflow as tf
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense, BatchNormalization

tf.__version__

'2.15.0'

## TASK 1: Obtain layer output


**COMPLETE** the following function so that, when given a TF `model` and input  `X` returns the output of the model at layer `layer_name` when feeding `X` to the model.


You **MUST RETURN** a `numpy` array, **NOT** a tensor.

**HINT**: Use the [`tf.keras.Model`](https://www.tensorflow.org/api_docs/python/tf/keras/Model) class like in the functional API with `outputs` from the desired layer.

**CHALLENGE**: Solve it with a single line of code (not counting the `import`)

In [43]:
def output_at_layer(X, model, layer_name):
    from tensorflow.keras.models import Model

    #COMPLETE..................
    r = Model(inputs=model.input, outputs=model.get_layer(layer_name).output).predict(X)
    return r
    #...................

check your answer manually. With the following model and weights below you should get this answer:


        >> output_at_layer(X, model, "layer_A")
        array([[0.91274303, 0.69886017, 0.8832942 ],
               [0.9311633 , 0.7634138 , 0.8924969 ],
               [0.85661894, 0.5696809 , 0.8091405 ],
               [0.8952345 , 0.6803274 , 0.8326857 ]], dtype=float32)

        >> output_at_layer(X, model, "layer_B")
        array([[0.87063193, 0.8240411 ],
               [0.8774254 , 0.83376545],
               [0.84875023, 0.7963983 ],
               [0.86286545, 0.81590414]], dtype=float32)

        >> output_at_layer(X, model, "layer_C")
        array([[0.8959839 , 0.65980244],
               [0.9032545 , 0.66435313],
               [0.8733646 , 0.646801  ],
               [0.8883195 , 0.6559416 ]], dtype=float32)

In [28]:
def get_model(n1,n2,n3):
    model = Sequential()
    model.add(Dense(n1, name="layer_A", activation="tanh", input_dim=2))
    model.add(Dense(n2, name="layer_B", activation="sigmoid"))
    model.add(Dense(n3, name="layer_C", activation="linear"))
    return model


w = [np.array([[0.3336241 , 0.26024526, 0.37238857],
               [0.6344426 , 0.67660165, 0.31070882]], dtype=np.float32),
     np.array([0.97280777, 0.3447949 , 0.91722184], dtype=np.float32),

     np.array([[0.12999585, 0.31851983],
               [0.7763866 , 0.8777575 ],
               [0.99977154, 0.65771514]], dtype=np.float32),
     np.array([0.36222705, 0.05885772], dtype=np.float32),

     np.array([[0.75918376, 0.02541249],
               [0.21730722, 0.45021895]], dtype=np.float32),
     np.array([0.05594416, 0.26667854], dtype=np.float32)]


X = np.array([[0.9269997 , 0.41239464],
              [0.8461177 , 0.64935404],
              [0.27092433, 0.34251866],
              [0.22509325, 0.6301328 ]], dtype=np.float32)


model=get_model(3,2,2)
model.set_weights(w)

In [29]:
output_at_layer(X, model, "layer_A")

1/1 [==============================] - 0s 48ms/step


array([[0.91274303, 0.69886017, 0.8832942 ],
       [0.9311633 , 0.7634138 , 0.8924969 ],
       [0.85661894, 0.5696809 , 0.8091405 ],
       [0.8952345 , 0.6803274 , 0.8326857 ]], dtype=float32)

In [30]:
# which corresponds to a tanh activation from the input data
np.tanh(X.dot(w[0])+w[1])

array([[0.912743  , 0.69886017, 0.8832942 ],
       [0.9311633 , 0.7634138 , 0.89249694],
       [0.8566189 , 0.5696809 , 0.8091404 ],
       [0.89523464, 0.6803274 , 0.8326857 ]], dtype=float32)

In [31]:
output_at_layer(X, model, "layer_B")

1/1 [==============================] - 0s 81ms/step


array([[0.87063193, 0.8240411 ],
       [0.8774253 , 0.83376545],
       [0.84875023, 0.7963982 ],
       [0.8628655 , 0.81590414]], dtype=float32)

In [37]:
# which corresponds to a sigmoid activation from the output of layer A
sigm = lambda x: 1/(1+np.exp(-x))
sigm(output_at_layer(X, model, "layer_A").dot(w[2])+w[3])


1/1 [==============================] - 0s 44ms/step


array([[0.870632  , 0.8240412 ],
       [0.8774254 , 0.8337655 ],
       [0.8487503 , 0.7963983 ],
       [0.86286545, 0.81590414]], dtype=float32)

In [33]:
output_at_layer(X, model, "layer_C")

1/1 [==============================] - 0s 56ms/step


array([[0.8959839 , 0.6598024 ],
       [0.90325445, 0.66435313],
       [0.8733646 , 0.646801  ],
       [0.8883195 , 0.6559416 ]], dtype=float32)

In [38]:
# which corresponds to a linear activation from the output of layer B
output_at_layer(X, model, "layer_B").dot(w[-2])+w[-1]

1/1 [==============================] - 0s 48ms/step


array([[0.8959839 , 0.65980244],
       [0.90325445, 0.66435313],
       [0.8733646 , 0.646801  ],
       [0.8883195 , 0.6559416 ]], dtype=float32)

**Registra tu solución en linea**

In [35]:
student.submit_task(namespace=globals(), task_id='T1');

## TASK 2: Implement batch normalization

Observe how we create a **ONE LAYER** model with **TANH** activation and batch normalization

In [39]:
def get_model(input_dim, n):
    model = Sequential()
    model.add(Dense(n, name="layer_A", activation="tanh", input_dim=input_dim))
    model.add(BatchNormalization())
    return model

we manually initialize it with random weights and apply it to some random input

In [40]:

input_dim = np.random.randint(3)+2
n = np.random.randint(5)+5
X = np.random.random((6,input_dim)).astype(np.float32)
print ("input_dim", input_dim, ", n", n)


input_dim 2 , n 7


In [41]:

model = get_model(input_dim=input_dim, n=n)
model.set_weights([np.random.random(i.shape) for i in model.get_weights()])
model(X).numpy()


array([[0.4378083 , 0.8955243 , 0.5728737 , 0.60093564, 0.65454495,
        0.4723038 , 1.178867  ],
       [0.3846605 , 0.8675044 , 0.5429286 , 0.3834408 , 0.6536793 ,
        0.4151498 , 1.3890388 ],
       [0.40126273, 0.9085615 , 0.54655623, 0.46377057, 0.65398693,
        0.42735827, 1.458081  ],
       [0.43236712, 0.9069957 , 0.56769854, 0.58343893, 0.65447056,
        0.46429342, 1.2775939 ],
       [0.40764204, 0.87356406, 0.55661684, 0.4810844 , 0.6540594 ,
        0.44045758, 1.2915756 ],
       [0.4516429 , 0.88299245, 0.5828916 , 0.6469652 , 0.65474343,
        0.4899244 , 0.9745528 ]], dtype=float32)

and we can extract the weights of the dense layer and the batch normalization layer

In [42]:

W, b, gamma, beta, moving_mean, moving_var = model.get_weights()
W.shape, b.shape, beta.shape, moving_mean.shape, moving_var.shape


((2, 7), (7,), (7,), (7,), (7,))

**COMPLETE** the following function **WITHOUT USING TENSORFLOW** such that you get the same output as the model above, given the input and the weights.

In specific, the Dense layer output must be

$$A = \text{tanh}(XW+b)$$

And the batch normalization layer after that output is

$$\frac{A-m_\mu}{\sqrt{m_\sigma+\varepsilon}}\gamma + \beta$$

You **MUST RETURN** a `numpy` array, **NOT** a tensor.

**CHALLENGE**: Solve it with one single line of Python code.

In [60]:
def apply_model(X, W, b, gamma, beta, moving_mean, moving_var, epsilon=1e-3):

  #COMPLETE..............
    r = gamma * (np.tanh (np.dot(X, W) + b) - moving_mean) / np.sqrt(moving_var + epsilon) + beta
    return r
    #......................

check manually your code, the output should be the same as above.

In [61]:
apply_model(X, W, b, gamma, beta, moving_mean, moving_var)

array([[0.43780825, 0.8955244 , 0.5728737 , 0.6009357 , 0.654545  ,
        0.47230375, 1.178867  ],
       [0.38466054, 0.8675044 , 0.5429286 , 0.38344085, 0.6536793 ,
        0.41514978, 1.3890387 ],
       [0.40126267, 0.90856147, 0.5465563 , 0.46377057, 0.65398693,
        0.42735827, 1.458081  ],
       [0.4323672 , 0.9069958 , 0.56769854, 0.5834391 , 0.65447056,
        0.46429342, 1.2775937 ],
       [0.40764204, 0.87356377, 0.55661684, 0.4810844 , 0.65405947,
        0.44045758, 1.2915757 ],
       [0.45164293, 0.8829925 , 0.5828916 , 0.6469653 , 0.65474343,
        0.4899244 , 0.97455275]], dtype=float32)

**Registra tu solución en linea**

In [62]:
student.submit_task(namespace=globals(), task_id='T2');

## TASK 3: Compute the Hessian

Complete the function below so that computes the Hessian of a function with respect to a set of variables. Remember that the Hessian is the matrix with all combinations of double partial derivatives. See [https://en.wikipedia.org/wiki/Hessian_matrix](https://en.wikipedia.org/wiki/Hessian_matrix)


The arguments for your code below:

- `expression_fn`: is a Python function that, when executed, will return a Tensor depending on the variables in `svars`.
- `svars`: a list of $n$ `tf.Variable`s against which  the derivatives are to be taken.

The result:

- a `numpy` array of dimension $n\times n$, containing in each position the value of the corresponding double derivative evaluated with the value attached to each variable in `svars`.

See the example call below to understand what you have to produce.

**NOTE**: Observe that `expression_fn` is a function that you **must call** inside some `GradientTape` to obtain the expresion. This needs to be done this way because `GradientTape` needs to _watch_ how expressions are built to be able to access the computational graph and compute the gradient. This is a technique which is very often used in Tensorflow.



**WARN**: You cannot use `tf.hessian` or `GradientTape.jacobian` or `sympy`. Do not use the name `hessian` to name any variable within your code.

**HINT 1**: use a `GradientTape` inside another `GradientTape`.

**HINT 2**: use `unconnected_gradients=tf.UnconnectedGradients.ZERO` as argument to `GradientTape.gradient` to have the variables not participating in an expresion result in gradient zero. For instance with $f=xy$, we have $\frac{\partial f}{\partial y\partial y}=0$, since $\frac{\partial f}{\partial y}=1$. Or if we have $f=x$ we have $\frac{\partial f}{\partial y\partial x}=0$, since $\frac{\partial f}{\partial y}=0$. If you do not include this argument, Tensorflow will return these values as `None` and you would have to fix them later.

In [67]:
def get_double_derivatives(expression_fn,svars):
    import tensorflow as tf

    #COMPLETE...............
    n = len(svars)
    result = np.zeros((n, n))

    with tf.GradientTape(persistent=True) as outer_tape:
        with tf.GradientTape() as inner_tape:
            inner_tape.watch(svars)
            outer_tape.watch(svars)

            expression = expression_fn()

        grads = inner_tape.gradient(expression, svars, unconnected_gradients=tf.UnconnectedGradients.ZERO)

    # Calculamos las segundas derivadas
    for i in range(n):
        for j in range(n):
            result[i, j] = outer_tape.gradient(grads[i], svars[j], unconnected_gradients=tf.UnconnectedGradients.ZERO)

    del outer_tape
    #...........................
    return result


check your code. The following expression

$$f = 2xy^2 + 3x\cos{y}$$

has as first derivatives:

- $\frac{\partial f }{\partial x} = 2y^2 +3\cos{y}$
- $\frac{\partial f }{\partial y} = 4xy - 3x\sin{y}$

and as second derivatives:

- $\frac{\partial f }{\partial x \partial x} = 0$
- $\frac{\partial f }{\partial x \partial y} = 4y - 3\sin{y}$
- $\frac{\partial f }{\partial y \partial x} = 4y - 3\sin{y}$
- $\frac{\partial f }{\partial y \partial y} = 4x - 3x\cos{y}$

which, when evaluated at $x=2$ and $y=-3$ yields

    [[  0     ,  -11.58],
     [ -11.58 ,   13.94]]

In [68]:
x = tf.Variable(2, dtype=tf.float32)
y = tf.Variable(-3, dtype=tf.float32)
expr = lambda: 2*x*y**2 + 3*x*tf.cos(y)

get_double_derivatives(expr, [x,y])

array([[  0.        , -11.57664013],
       [-11.57664013,  13.93995476]])

**Registra tu solución en linea**

In [69]:
student.submit_task(namespace=globals(), task_id='T3');